### PR TITLE
PR for milestone 1

### PR DESCRIPTION
**Pull request by abouhid**
I had some issues with the development branch / feature_branch not having the same histories (since I pushed a local folder which I had started the app). After taking too long to fix this minor issue I decided to just change a minor thing in the feature_branch to be able to create this PR. Sorry for this technical issue, but the main part is working since the Heroku app is running fine

### CODE REVIEW

**Comment by bellom** [comment]
Hi @abouhid ,

### This CRR has been marked as invalid because of the following reasons

1.**Add linter's check** checkout this [linters-config#troubleshooting](https://github.com/microverseinc/linters-config#troubleshooting) for help. Example below;
image


**NOTE:** Microverse has moved on to Github actions for continuous deployment please use it. 
image

https://github.com/microverseinc/linters-config/tree/master/react-redux


2. **Let's make your repo looks professional by applying all the 3 basic rules, kindly update your `README` file and remove unnecessary content**.
Checkout out the below link for help, feel free to follow this [template](https://github.com/microverseinc/readme-template) from pathwright
And don't forget to add your heroku live link.

image

https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243642/

**Review by trekab — CHANGES_REQUESTED** [review]
### Changes Required! :recycle: 
Hi @abouhid! Sorry about the challenges you faced with your branches. There are some changes I'd like you to consider to finish this milestone:
- [ ] Because you deleted the `public` folder, the `npm start` command couldn't find the required `index.html` file. ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/react_reducx/calculator/milestone1/app-runs.png) from [pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/44896085/))
- [x] Please share the live link to your deployed app in the README file. ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/react_reducx/calculator/milestone1/app-deployed.png) from [pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/44896085/))

__Kindly make the necessary changes and submit another code review request.__
_Feel free to reach me on slack for any inquiries about this review._ :wink: 
__Treasure Kabareebe__
[Portfolio](https://trekab.github.io/portfolio/) | [LinkedIn](https://www.linkedin.com/in/treasure-kabareebe/) | [Twitter](https://twitter.com/TKabareebe)

**Comment by abouhid** [comment]
> ### Changes Required! 
> Hi @abouhid! Sorry about the challenges you faced with your branches. There are some changes I'd like you to consider to finish this milestone:
> 
> * [ ]  Because you deleted the `public` folder, the `npm start` command couldn't find the required `index.html` file. ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/react_reducx/calculator/milestone1/app-runs.png) from [pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/44896085/))
> * [x]  Please share the live link to your deployed app in the README file. ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/react_reducx/calculator/milestone1/app-deployed.png) from [pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/44896085/))
> 
> **Kindly make the necessary changes and submit another code review request.**
> _Feel free to reach me on slack for any inquiries about this review._ 
> **Treasure Kabareebe**
> [Portfolio](https://trekab.github.io/portfolio/) | [LinkedIn](https://www.linkedin.com/in/treasure-kabareebe/) | [Twitter](https://twitter.com/TKabareebe)

I am sorry for these silly mistakes, it is late here so I forgot to edit the README.
About deleting the public folder, it was probably because of some npm packages I had to install to make eslint work, since the one provided was not working. Hope everything works now!

**Review by addod19 — APPROVED** [review]
## Status: Approved :trophy: :balloon: 

Hi @abouhid, congratulations on setting up the project and installing the needed packages :slightly_smiling_face: Since you have fixed the comments identified by the previous TSE's, I hereby approve the project :+1: 
[Optional]
- Kindly add a gitignore file so we can hide the node_modules
- Kindly delete all unnecessary files like the logos, we still have them

Kindly move to the next milestone :fireworks: 
_Happy coding_ :man_technologist: 
[Daniel Larbi Addo](https://www.linkedin.com/in/daniel-larbi-addo/)

**Pull request merged**
