### PR TITLE
PR for Milestone 5 of React Calculator Project

### PR DESCRIPTION
**Pull request by abouhid**
This last PR implemented:
- handleClick function to the App component
- Display value on screen
- onClick passed to each button 
- logic for extreme cases
- more styling

### CODE REVIEW

**Review by trekab — CHANGES_REQUESTED** [review]
### Changes Required! :tada: 
Hi @abouhid! Your effort so far is commendable! :+1: There are just a few touches for you to make to complete this milestone. These include:
- [ ] Add the `.vscode` folder to `.gitignore` ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/general/gitignore.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243643/))
- [ ]  Your `ButtonPanel`'s handleClick function should accept a buttonName as an argument and return a clickHandler from props. ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/react_reducx/calculator/milestone5/panel/implementHandleClick.png))
- [ ] __[Optional]__ Use arrow functions to set state. This makes working with the `this` keyword more predictable for your class-based components. Making use of ES6+ features is highly recommended since they implicitly encourage using best JS programming practices.

__Kindly make the necessary changes and submit another code review request.__
_Feel free to reach me on slack for any inquiries about this review._ :wink: 
__Treasure Kabareebe__
[Portfolio](https://trekab.github.io/portfolio/) | [LinkedIn](https://www.linkedin.com/in/treasure-kabareebe/) | [Twitter](https://twitter.com/TKabareebe)

**Comment by abouhid** [comment]
I do not think it is necessary to apply this change to the Button Panel, since It is just being a container for the function to be passed on to the Button Component, I simply sent it through props from App.js to Button.js. Therefore, the change required will be redundant

**Review by rOluochKe — CHANGES_REQUESTED** [review]
Hello @abouhid 
### You have done well so far :clap: However, you have a few issues to fix:-
- [ ] Add .vscode in .gitignore file. it is still among the files and it is unwanted.
- [ ] We recommend the use of es6 arrow function rather than the function keyword. See below:
`const Operate = (numberOne, numberTwo, operation) => { # your code }`
- [ ] Online version of the app is not working, see the image below for the error message being displayed
online
### Make the changes and submit for another code review.
- Good luck.

**Review by rOluochKe — APPROVED** [review]
### You got it right. The project has been approved. Congratulations :boom: :100:
### Merge and submit the project. Good luck with the next one.
- Happy coding!

**Pull request merged**
